singleQuote: false
semi: true
printWidth: 80
trailingComma: es5
tabWidth: 2
quoteProps: "as-needed"
jsxSingleQuote: false
bracketSpacing: true
bracketSameLine: false
arrowParens: "always"
endOfLine: "lf"
singleAttributePerLine: false
importOrder: ["^@core/(.*)$", "^@server/(.*)$", "^@ui/(.*)$", "^[./]"],
importOrderSeparation: true
importOrderSortSpecifiers: true
